CREATE TABLE `Member_Data` (
  `Member_ID` int NOT NULL,
  `Brand_ID` int NOT NULL,
  `Brand_Member_ID` varchar(50) NOT NULL COMMENT 'The combination of brand_member_id and hea_member_id should be unique within the brand system',
  `Master_Member_ID` varchar(50) DEFAULT NULL,
  `Member_Name` varchar(250) NOT NULL,
  `Phone` varchar(15) DEFAULT NULL,
  `Email_Address` varchar(50) DEFAULT NULL,
  `Member_Since` date DEFAULT NULL,
  `status_id` int DEFAULT '1',
  `Member_Last_Purchase` date DEFAULT NULL COMMENT 'This column stores the date the Member last ordered through a brand. The dashboard will show only month and year, but the Brands can pass a fully formatted DATE data type.',
  `Sales_Rep` varchar(255) DEFAULT NULL,
  `Business_Type` varchar(255) DEFAULT NULL,
  `Plan_Type_Code` varchar(50) DEFAULT NULL,
  `Association_Group_Code` varchar(50) DEFAULT NULL,
  `Email_Statement_Flag` tinyint(1) DEFAULT '0',
  `Comments` longtext,
  `IsInactive` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`Member_ID`),
  UNIQUE KEY `Member_IDX6` (`Brand_Member_ID`,`Brand_ID`),
  UNIQUE KEY `Member_IDX5` (`Master_Member_ID`),
  KEY `Member_IDX2` (`status_id`),
  KEY `Member_IDX3` (`Member_Name`),
  KEY `Member_IDX1` (`Brand_ID`),
  KEY `Member_IDX7` (`Plan_Type_Code`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `contact_queue` (
  `Contact_ID` int(11) NOT NULL AUTO_INCREMENT,
  `Contact_Type` varchar(50) NOT NULL,
  `Contact_Fname` varchar(50) DEFAULT NULL,
  `Contact_Lname` varchar(50) DEFAULT NULL,
  `Contact_Email` varchar(50) DEFAULT NULL,
  `Contact_DOB` varchar(50) DEFAULT NULL,
  `Contact_Question` text DEFAULT NULL,
  `Contact_Response` text DEFAULT NULL,
  `Final_Prompt` text DEFAULT NULL,
  `Final_Response` text DEFAULT NULL,
  `Evaluation` int(2) NOT NULL DEFAULT 0,
  `Creation_Date` timestamp NULL DEFAULT NULL,
  `Processed_Date` timestamp NULL DEFAULT NULL,
  `Status` varchar(10) DEFAULT 'Open',
  `Payload` text DEFAULT NULL,
  PRIMARY KEY (`Contact_ID`),
  KEY `Contact_Email` (`Contact_Email`),
  KEY `Contact_Lname` (`Contact_Lname`),
  KEY `Contact_Fname` (`Contact_Fname`),
  KEY `Creation_Date` (`Creation_Date`),
  KEY `Status` (`Status`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

